# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-28 06:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0008_auto_20180328_0642'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Booking_start', models.DateTimeField()),
                ('Booking_end', models.DateTimeField()),
                ('Approved', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['Booking_start'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Room_no', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='Room_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.Room'),
        ),
        migrations.AddField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Profile'),
        ),
    ]
