# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-27 15:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Booking_start', models.DateTimeField()),
                ('Booking_end', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='MyModel',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='room_no',
            new_name='Room_no',
        ),
        migrations.AddField(
            model_name='booking',
            name='Room_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Room'),
        ),
        migrations.AddField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Profile'),
        ),
    ]
