# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-27 16:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20180327_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='Approved',
            field=models.BooleanField(default=False),
        ),
    ]
