# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-28 06:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_booking_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='Room_no',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='user',
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
