# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-28 09:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20180328_0642'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(default='Not Provided.', max_length=254),
        ),
    ]
